#!/bin/sh
export USER="nobody"
export LOGIN="rick"; 
export PASS="rick"; 
export PORT=7400
export MONGODB=sadmin55
#${RANDOM}
#export COMMAND="export PORT=4001; cd ~ && rm -rf ServerAdministration; git clone https://github.com/binRick/ServerAdministration.git && cd ServerAdministration && npm install && npm start"; 
#export COMMAND1="ls -al /etc"
#export COMMAND2="ls -al /"
#ls -al --color"
#git clone https://github.com/binRick/ServerAdministration.git"
# && cd ServerAdministration && npm install && npm start"; 
exec setuidgid ${USER} npm start 2>&1
